resources = {
    "السنة الأولى": {
        "الفصل الأول": {
            "theoretical": {
                "⚡ فيزياء كهربائية": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [107, 108, 109, 110, 111, 112],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "💻 برمجة 1": {
                    "gate": [0],
                    "komit": [61, 62, 63, 64, 65, 66],
                    "student_written": [94, 95, 96, 97, 98, 99],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "📊 تحليل 1": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [131, 132],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "🖥 مبادئ عمل الحاسوب": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [120, 121, 122, 123, 135],
                    "summaries": [0],
                    "exams": [8],
                    "notes": [41],
                },
                "➗ جبر لا خطي": {
                    "gate": [0],
                    "komit": [53, 54, 55, 56, 57, 58, 59],
                    "student_written": [78, 79, 80, 81, 82, 83, 84, 85, 86],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "🇬🇧 لغة انجليزية 1": {
                    "gate": [0],
                    "komit": [6],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [6],
                    "notes": [39],
                },
                "🇸🇦 لغة عربية": {
                    "gate": [41],
                    "komit": [68],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
            },
            "practical": {
                "⚡ فيزياء كهربائية": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [114, 115, 116, 117, 118],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "💻 برمجة 1": {
                    "gate": [33, 34, 35, 36, 37, 38, 39],
                    "komit": [0],
                    "student_written": [101, 102, 103, 104, 105],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "📊 تحليل 1": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "🖥 مبادئ عمل الحاسوب": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [125, 126, 127, 128, 129],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "➗ جبر لا خطي": {
                    "gate": [0],
                    "komit": [0],
                    "student_written": [89, 90, 91, 92],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
            },
        },
        "الفصل الثاني": {
            "theoretical": {
                "➗ جبر خطي": {
                    "gate": [0],
                    "komit": [5, 7, 8, 9, 10],
                    "student_written": [43, 44, 45, 46, 47, 48, 49],
                    "summaries": [72, 73, 74, 75, 76],
                    "exams": [0],
                    "notes": [0],
                },
                "⚡ فيزياء انصاف نواقل": {
                    "gate": [0],
                    "komit": [45, 46, 47],
                    "student_written": [0],
                    "summaries": [11, 12],
                    "exams": [0],
                    "notes": [37],
                },
                "💻 برمجة 2": {
                    "gate": [22, 23, 24, 25, 26],
                    "komit": [17, 18, 19, 20, 21, 22],
                    "student_written": [58, 59, 60, 61, 62, 63, 64],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [24, 25, 26, 27, 28],
                },
                "📊 تحليل 2": {
                    "gate": [0],
                    "komit": [30, 31, 32, 33, 34, 35],
                    "student_written": [66, 67, 68, 69, 70],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "🇬🇧 لغة انجليزية 2": {
                    "gate": [0],
                    "komit": [49],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
            },
            "practical": {
                "➗ جبر خطي": {
                    "gate": [30, 31],
                    "komit": [12, 13, 14, 15],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "⚡ فيزياء انصاف نواقل": {
                    "gate": [0],
                    "komit": [45, 46, 47],
                    "student_written": [51, 52, 53, 54, 55, 56],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
                "💻 برمجة 2": {
                    "gate": [28],
                    "komit": [24, 25, 26, 27, 28],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [30, 31, 32, 33, 34, 35],
                },
                "📊 تحليل 2": {
                    "gate": [0],
                    "komit": [37, 38, 39, 40, 41, 42, 43],
                    "student_written": [0],
                    "summaries": [0],
                    "exams": [0],
                    "notes": [0],
                },
            },
        },
    },
}

channel_ids = {
    "gate": -1002739707573,
    "komit": -1002883141998,
    "student_written": -1002701154329,
    "summaries": -1002890234972,
    "exams": -1002449310532,
    "notes": -1002834270732,
}

temporary_culture_doc = 51
